### ISSUE TITLE
404 (Not Found) fonts in css_variables.css in 11.29.0 version

### ISSUE THREAD

**Issue by c5346163** [SAP/theming-base-content#21]
Hi, 

I am using Angular 19 on Node 22 and tried to update this package to the newest version. 

Current package.json
```
"@fundamental-ngx/core": "0.55.6",
"@fundamental-ngx/datetime-adapter": "0.55.6",
"@fundamental-ngx/i18n": "0.55.6",
"fundamental-styles": "0.39.2",
"@angular/core": "19.2.6",
```

angular.json
```
	"assets":[
		"src/favicon.ico",
		"src/assets",
		"src/Staticfile",
		{
			"glob":"**/css_variables.css",
			"input":"./node_modules/@sap-theming/theming-base-content/content/Base/baseLib/",
			"output":"./assets/theming-base/"
		},
		{
			"glob":"**/*",
			"input":"./node_modules/fundamental-styles/dist/theming/",
			"output":"./assets/fundamental-styles-theming/"
		},
		{
			"glob":"fundamental-styles-*.css",
			"input":"./node_modules/fundamental-styles/dist/",
			"output":"./assets/fundamental-styles/"
		},
		{
			"glob":"**/*",
			"input":"src/assets",
			"output":"/assets/"
		}
	],
	"styles":[
		"node_modules/fundamental-styles/dist/fundamental-styles.css",
		"src/styles.scss",
		{
			"input":"src/styles/fonts.scss",
			"inject":false,
			"bundleName":"sap_horizon_fonts"
		}
	]
```

On version "@sap-theming/theming-base-content": "11.28.2", everything seems to work correctly but when I update to 11.29.0 I have this issue in the console:

![Image](https://github.com/user-attachments/assets/0d72f81e-31da-4ac5-b6f8-6c91d97d0f7d)

from /assets/theming-base/sap_horizon/css_variables.css

**Comment by c5346163** [comment]
I was able to fix it by adding to angular.json
```
{
                "glob": "**/*",
                "input": "./node_modules/@sap-theming/theming-base-content/content/Base/baseLib/baseTheme/fonts",
                "output": "./assets/theming-base/baseTheme/fonts"
}
```

![Image](https://github.com/user-attachments/assets/9fce6ce0-1e2d-403f-8e5c-af2b1d824f7c)


Without that if I only use:

```
{
                "glob": "**/css_variables.css",
                "input": "./node_modules/@sap-theming/theming-base-content/content/Base/baseLib/",
                "output": "./assets/theming-base/"
},
```
My build wouldn't cointain baseTheme cousing errors: 
![Image](https://github.com/user-attachments/assets/adb4757e-93fa-447d-bff7-6a96524167fa)


Tbh I am not sure on what version this error persist because I updated from "11.13.0". If it's by design we can close it.

**Comment by droshev** [comment]
from the [commit](https://github.com/SAP/theming-base-content/commit/a5efc97738c42acfa73e319a06254570726d3a0e) i don't see a change. Let me check with the colleagues responsible.

**Comment by dominikschreiber** [comment]
Hi @c5346163,

with 11.29.0, the css_variables.css files include `@font-face` definitions for the fonts included in the theming-base-content, e.g. for [72 in sap_horizon](https://github.com/SAP/theming-base-content/blob/11.29.0/content/Base/baseLib/sap_horizon/css_variables.css#L21-L27):
```css
@font-face {
  font-family: '72';
  font-style: normal;
  font-weight: 400;
  src: url(../baseTheme/fonts/72-Regular.woff2) format('woff2'), url(../baseTheme/fonts/72-Regular.woff) format('woff'), local('72');
  unicode-range: U+00, U+0D, U+20-7E, U+A0-FF, U+131, U+152-153, U+161, U+178, U+17D-17E, U+192, U+237, U+2C6, U+2DC, U+3BC, U+1E9E, U+2013-2014, U+2018-201A, U+201C-201E, U+2020-2022, U+2026, U+2030, U+2039-203A, U+2044, U+20AC, U+2122;
}
```
Most of those fonts are located in content/Base/baseLib/**baseTheme/fonts**.

**The theming-base-content assumes that the files it includes are available** (hence the relative URL from `sap_horizon/css_variables` to `../baseTheme/fonts/72-Regular.woff2`). You have to make sure that this assumption holds true – which you did with your change to your angular.json. So I'll close this issue.
